version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.6.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  web:
    build: ../..
    volumes:
      - ./models/:/app/models
    entrypoint:
      - python
      - ./examples/coffee_bot/app.py
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ACTION_ENDPOINT=http://localhost:8080/webhook
      - APP_DIR=./examples/coffee_bot
    restart: always
